version: "3"
services:
  golang:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    image: golang
    container_name: api
    volumes:
      - ./src:/go/src
    ports:
      - "8080:8080"
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: mysql
    container_name: db
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=odoro-tree
      - MYSQL_USER=odoro-tree
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    tty: true
