openapi: 3.0.3
info:
  title: Odoro-tree-api
  description: odoro-tree
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: localhost
  - url: http://59.106.209.98:8080
    description: Test environment
tags:
  - name: trees
    description: Tree's interface
  - name: branches
    description: Branch's interface
  - name: leaves
    description: Leaf's interface
paths:
  /trees:
    get:
      tags:
        - trees
      summary: Find trees
      operationId: GetTrees
      description: Return all trees' data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tree'
    post:
      tags:
        - trees
      summary: Create a tree
      operationId: PostTree
      description: Create a tree with a request's data
      requestBody:
        description: A tree's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TreeRequest'
      responses:
        '201':
          description: Return the created data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tree'
  /trees/{tree_id}:
    get:
      tags:
        - trees
      summary: Get a tree
      operationId: GetTree
      description: Return the data of the tree specified
      parameters:
        - in: path
          name: tree_id
          required: true
          schema:
            type: int
            description: ID of the tree
            example: 1
      responses:
        '200':
          description: Return the data specified
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tree'

    put:
      tags:
        - trees
      summary: Update a tree
      operationId: PutTree
      description: Update a tree's data
      parameters:
        - in: path
          name: tree_id
          required: true
          schema:
            type: int
            description: ID of the tree
            example: 1
      requestBody:
        description: The updated tree's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tree'
      responses:
        '200':
          description: Return the updated data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tree'
    delete:
      tags:
        - trees
      summary: Delete a tree
      operationId: DeleteTree
      description: Delete the tree specified
      parameters:
        - in: path
          name: tree_id
          required: true
          schema:
            type: int
            description: ID of the tree
            example: 1
      responses:
        '204':
          description: Successfully deleted
  /trees/{tree_id}/childbranches:
    get:
      tags:
        - trees
      summary: Find childbranches
      operationId: GetChildBranches
      description: Return all the child branches
      parameters:
        - in: path
          name: tree_id
          required: true
          schema:
            type: int
            description: ID of the parent tree
            example: 1
      responses:
        '200':
          description: Return all child branches' data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Branch'
  /branches:
    get:
      tags:
        - branches
      summary: Find branches
      operationId: GetBranches
      description: Return all branches' data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Branch'
    post:
      tags:
        - branches
      summary: Create a branch
      operationId: PostBranch
      description: Create a branch with a request's data
      requestBody:
        description: A branch's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BranchRequest'
      responses:
        '201':
          description: Return the created data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Branch'
  /branches/{branch_id}:
    get:
      tags:
        - branches
      summary: Get a branch
      operationId: GetBranch
      description: Return the data of the branch specified
      parameters:
        - in: path
          name: branch_id
          required: true
          schema:
            type: int
            description: ID of the branch
            example: 1
      responses:
        '200':
          description: Return the data specified
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Branch'

    put:
      tags:
        - branches
      summary: Update a branch
      operationId: PutBranch
      description: Update a branch's data
      parameters:
        - in: path
          name: branch_id
          required: true
          schema:
            type: int
            description: ID of the branch
            example: 1
      requestBody:
        description: The updated branch's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
      responses:
        '200':
          description: Return the updated data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Branch'
    delete:
      tags:
        - branches
      summary: Delete a branch
      operationId: DeleteBranch
      description: Delete the branch specified
      parameters:
        - in: path
          name: branch_id
          required: true
          schema:
            type: int
            description: ID of the branch
            example: 1
      responses:
        '204':
          description: Successfully deleted
  /branches/{branch_id}/childleaves:
    get:
      tags:
        - branches
      summary: Find childleaves
      operationId: GetChildLeaves
      description: Return all the child leaves
      parameters:
        - in: path
          name: branch_id
          required: true
          schema:
            type: int
            description: ID of the parent branch
            example: 1
      responses:
        '200':
          description: Return all child leaves' data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChildLeaf'
  /leaves:
    get:
      tags:
        - leaves
      summary: Find leaves
      operationId: GetLeaves
      description: Return all leaves' data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leaf'
    post:
      tags:
        - leaves
      summary: Create a leaf
      operationId: PostLeaf
      description: Create a leaf with a request's data
      requestBody:
        description: A leaf's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeafRequest'
      responses:
        '201':
          description: Return the created data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Leaf'
  /leaves/{leaf_id}:
    get:
      tags:
        - leaves
      summary: Get a tree
      operationId: GetLeaf
      description: Return the data of the tree specified
      parameters:
        - in: path
          name: leaf_id
          required: true
          schema:
            type: int
            description: ID of the leaf
            example: 1
      responses:
        '200':
          description: Return the data specified
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Leaf'
    put:
      tags:
        - leaves
      summary: Update a leaf
      operationId: PutLeaf
      description: Update a leaf's data
      parameters:
        - in: path
          name: leaf_id
          required: true
          schema:
            type: int
            description: ID of the leaf
            example: 1
      requestBody:
        description: The updated leaf's data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Leaf'
      responses:
        '200':
          description: Return the updated data
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Leaf'
    delete:
      tags:
        - leaves
      summary: Delete a leaf
      operationId: DeleteLeaf
      description: Delete the leaf specified
      parameters:
        - in: path
          name: leaf_id
          required: true
          schema:
            type: int
            description: ID of the leaf
            example: 1
      responses:
        '204':
          description: Successfully deleted
components:
  schemas:
    Tree:
      type: object
      required:
        - tree_id
        - name
      properties:
        tree_id:
          type: int
          description: ID of a tree
          example: 1
        name:
          type: string
          description: Name of a tree
          example: 
    TreeRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of a tree
          example:
    Branch:
      type: object
      required:
        - branch_id
        - parent_tree_id
      properties:
        branch_id:
          type: int
          description: ID of a branch
          example: 1
        parent_tree_id:
          type: int
          description: ID of a parent tree
          example: 1
    BranchRequest:
      type: object
      required:
        - parent_tree_id
      properties:
        parent_tree_id:
          type: int
          description: ID of a parent tree
          example: 1
    Leaf:
      type: object
      required:
        - leaf_id
        - front_content
        - back_content
        - rating
        - parent_branch_id
      properties:
        leaf_id:
          type: int
          description: ID of a leaf
          example: 1
        front_content:
          type: string
          description: Front content
        back_content:
          type: string
          description: Back content
        rating:
          type: int
          description: Rating of a leaf
          example: 1
        parent_branch_id:
          type: int
          description: ID of a parent branch
          example: 1
    LeafRequest:
      type: object
      required:
        - front_content
        - back_content
        - rating
        - parent_branch_id
      properties:
        front_content:
          type: string
          description: Front content
        back_content:
          type: string
          description: Back content
        rating:
          type: int
          description: Rating of a leaf
          example: 1
        parent_branch_id:
          type: int
          description: ID of a parent branch
          example: 1
    ChildLeaf:
      type: object
      required:
        - leaf_id
        - rating
      properties:
        leaf_id:
          type: int
          description: ID of a leaf
          example: 1
        rating:
          type: int
          description: Rating of a leaf
          example: 1
